In [1]:
import numpy as np

# How to creat an array

In [3]:
a=np.array([1,2,3,4,5,6])
print(a)
print(type(a))
print(a.shape)#means the dimensions of the array

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
(6,)


In [9]:
b=np.array([[1,2,2,3],[1,2,3]])
print(b.shape)
print(b[1][1])

(2,)
2


In [12]:
a=np.zeros((3,3))
print(a)
b=np.ones((2,3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
# Array of some function
c=np.full((2,3),5)
print(c)

[[5 5 5]
 [5 5 5]]


In [14]:
# Identity matrix -size/square matrix
d=np.eye(4)
print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [15]:
# Random matrix
randomMatrix=np.random.random((2,3))
print(randomMatrix)

[[0.36671042 0.5768809  0.81383324]
 [0.41159365 0.69700196 0.35892662]]


In [18]:
print(randomMatrix[ : ,1])

[0.5768809  0.69700196]


In [21]:
randomMatrix[1,1: ] = 1
print(randomMatrix)

[[0.36671042 0.5768809  0.81383324]
 [0.41159365 1.         1.        ]]


In [23]:
z=np.zeros((3,3))
print(z)
z[1,1:]=2
z[0,2]=1
z[2,2]=3
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 1.]
 [0. 2. 2.]
 [0. 0. 3.]]


In [24]:
# datatypes
s=np.zeros((3,3),dtype=np.int64)
print(s.dtype)
# by default the array is float

int64


In [27]:
# Mathematical Operation
x=np.array([[1,2],[3,4]])
y=np.array([[4,5],[6,7]])
print(x+y)
print(np.add(x,y))
print(np.subtract(x,y))

[[ 5  7]
 [ 9 11]]
[[ 5  7]
 [ 9 11]]
[[-3 -3]
 [-3 -3]]


In [28]:
print(x*y)
print(np.multiply(x,y))#element wise

[[ 4 10]
 [18 28]]
[[ 4 10]
 [18 28]]


In [29]:
print(np.divide(x,y))#element wise

[[0.25       0.4       ]
 [0.5        0.57142857]]


In [30]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [31]:
# Matrix multiplication /dot products
print(x.dot(y))
print(np.dot(x,y))

[[16 19]
 [36 43]]
[[16 19]
 [36 43]]


In [32]:
# Multiplication of two vectors
a=np.array([1,2,3,4,5])
b=np.array([1,2,3,4,5])
print(np.dot(a,b))#gives a scalar

55


In [35]:
print(np.sum(a))
print(np.sum(x,axis=0))
print(np.sum(x,axis=1))

15
[4 6]
[3 7]


In [58]:
w=np.stack((a,b),axis=0)
print(w)

[[1 2 3 4 5]
 [1 2 3 4 5]]


In [56]:
np.stack((a,b**2),axis=1)

array([[ 1,  1],
       [ 2,  4],
       [ 3,  9],
       [ 4, 16],
       [ 5, 25]])

In [57]:

w=w.reshape((5,2))
print(w)

[[1 2]
 [3 4]
 [5 1]
 [2 3]
 [4 5]]


# Numpy Random Module
- rand:random values in a given shape
- randn:return a sample from the 'standard normal' distribution
- randint: return random integers from low(inclusive) to high(exclusive)
- random: return random floats in half open intervals[0.0,1.0)
- choice: Generates a random sample from a given 1-D array
- shuffle: shuffles the content of a sequence                                                      

In [60]:
a= np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [64]:
np.random.shuffle(a)
print(a)

[3 4 8 7 9 5 1 2 0 6]


In [66]:
f=np.random.randn(2,3)
print(f)

[[ 0.14109626 -0.10278471 -0.0532648 ]
 [-2.29384761  2.86299688 -0.20622258]]


In [70]:
np.random.seed(1)
d=np.random.randint(5,10,3)# we will get three numbers which are in 5-10 range
print(d)

[8 9 5]


In [69]:
# randomly pick one element from an array
print(np.random.choice(d))

5


# Some More Numpy Functions - Statistics
- min,max
- mean
- median
- average
- varience
- standard deviation

TypeError: data type not understood