# Linear Algebra
- Scaler a single number denoted as x
- vectors is a single dimensional array of scalers or represented as a column array but can be representd as a list as well

In [1]:
import numpy as np

In [3]:
x1=np.array([4,5,6])
print(x1)
print(x1.shape)

[4 5 6]
(3,)


In [6]:
# we will represent a vector as a column vector,that has multiple rows
x=np.array([[4],[5],[6]])
print(x)
print(x.shape)
print(x[0])
print(x[0][0])

[[4]
 [5]
 [6]]
(3, 1)
[4]
4


### Tensors are arrays with more than two axis unlike matrises which have only tow axis(2d)

In [12]:
# here x is a matrix
X=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(X)
print(X.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [13]:
# and here T is a tensor
T=np.array([[[1,2,3,],[4,5,6]],[[2,3,4],[7,8,9]]])
print(T)
print(T.shape)

[[[1 2 3]
  [4 5 6]]

 [[2 3 4]
  [7 8 9]]]
(2, 2, 3)


### Transpose

In [15]:
print(X)
Xt=np.transpose(X)
print(Xt)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [18]:
y=x.reshape((-1,1))
print(y)
print(np.transpose(y))
# y was a column vector and if we take transpose it becomes a row vector

[[4]
 [5]
 [6]]
[[4 5 6]]


## Broadcasting
- you can add a scalar to a vector and numpy will add it to each element in the vector 
- similarly you can add a vector to a matrix,and numpy will add the vector to each 
  column of the matrix

In [19]:
l=[1,2,3,4]
l=np.array(l)
l=l+5
print(l)

[6 7 8 9]


In [21]:
l2=np.array([[1,2,3],[7,8,9]])
np.sqrt(l2)

array([[1.        , 1.41421356, 1.73205081],
       [2.64575131, 2.82842712, 3.        ]])

# Matrix multiplication
- C=AB is only defined when A(m,n) and B(n,p)
- C is of shape (m,p)


In [22]:
x1=np.array([[4,5,7],[10,11,13],[56,80,90]])
x2=np.array([[40,50,70],[100,110,130],[290,801,820]])

In [25]:
print(x1.shape)
print(x2.shape)
print(x1)
print(x2)

(3, 3)
(3, 3)
[[ 4  5  7]
 [10 11 13]
 [56 80 90]]
[[ 40  50  70]
 [100 110 130]
 [290 801 820]]


In [26]:
prod=np.dot(x1,x2)
print(prod)

[[ 2690  6357  6670]
 [ 5270 12123 12790]
 [36340 83690 88120]]


### Element wise multiplication:Hadamard product
element wise multiplication A.B
Notice how numpy uses the * for this .Imoportant to be careful and not to be confused with 
matix multiplication

In [28]:
x1=np.array([[4,5,7],[10,11,13],[56,80,90]])
y1=np.eye(3,3)
y1=y1+1
y1=y1*2
print(y1)

[[4. 2. 2.]
 [2. 4. 2.]
 [2. 2. 4.]]


In [29]:
print(x1*y1)

[[ 16.  10.  14.]
 [ 20.  44.  26.]
 [112. 160. 360.]]


# Norm
https://wikimedia.org/api/rest_v1/media/math/render/svg/9f2d83bfa397bdf021046004b9a365079cab6a22


In [30]:
l=np.array([-5,3,10])
l2=np.linalg.norm(x)# by default it is l2 norm
print(l2)

8.774964387392123


In [33]:
np.linalg.norm(l,ord=1)#l1 norm

18.0

In [34]:
np.linalg.norm(l,ord=np.inf)# max-norm

10.0