## Pandas
- It is a library to work under tabular data.
- DataFrame- Special Object to store data in tabular form(rows & columns)

In [2]:
import numpy as np
import pandas as pd

In [3]:
# try to create a data frame
user_data={
    'MarksA':np.random.randint(1,100,5),
    'MarksB':np.random.randint(50,100,5),
    'MarksC':np.random.randint(1,100,5)
}

In [4]:
print(user_data)

{'MarksA': array([ 8, 50, 43, 43, 43]), 'MarksB': array([81, 83, 97, 75, 51]), 'MarksC': array([64, 38, 28, 34, 64])}


In [5]:
df=pd.DataFrame(user_data)
print(df)

   MarksA  MarksB  MarksC
0       8      81      64
1      50      83      38
2      43      97      28
3      43      75      34
4      43      51      64


In [6]:
df.head()

MarksA  MarksB  MarksC
0       8      81      64
1      50      83      38
2      43      97      28
3      43      75      34
4      43      51      64

In [7]:
# Creat a csv from a data frame
df.to_csv('marks.csv')

In [9]:
# to read a csv
my_data=pd.read_csv('marks.csv')
my_data

Unnamed: 0  MarksA  MarksB  MarksC
0           0       8      81      64
1           1      50      83      38
2           2      43      97      28
3           3      43      75      34
4           4      43      51      64

In [12]:
# To drop a column
my_data2=my_data.drop(columns='Unnamed: 0')
my_data2

MarksA  MarksB  MarksC
0       8      81      64
1      50      83      38
2      43      97      28
3      43      75      34
4      43      51      64

In [13]:
my_data.describe()

Unnamed: 0     MarksA     MarksB     MarksC
count    5.000000   5.000000   5.000000   5.000000
mean     2.000000  37.400000  77.400000  45.600000
std      1.581139  16.712271  16.816658  17.169741
min      0.000000   8.000000  51.000000  28.000000
25%      1.000000  43.000000  75.000000  34.000000
50%      2.000000  43.000000  81.000000  38.000000
75%      3.000000  43.000000  83.000000  64.000000
max      4.000000  50.000000  97.000000  64.000000

In [14]:
my_data.tail(n=2)# shows the last 2 datas

Unnamed: 0  MarksA  MarksB  MarksC
3           3      43      75      34
4           4      43      51      64

In [15]:
# Row
df.iloc[3]

MarksA    43
MarksB    75
MarksC    34
Name: 3, dtype: int64

In [16]:
# Row along with column
df.iloc[3,2]# or df.iloc[3][2]

34

In [17]:
# Incase column index is not known
idx=[df.columns.get_loc('MarksB'),df.columns.get_loc('MarksC')]
print(idx)

[1, 2]


In [19]:
# Sclicing Operation
df.iloc[1:3,idx]

MarksB  MarksC
1      83      38
2      97      28

In [20]:
my_data.sort_values(by=['MarksA'],ascending=True)# If false it would be descending

Unnamed: 0  MarksA  MarksB  MarksC
0           0       8      81      64
2           2      43      97      28
3           3      43      75      34
4           4      43      51      64
1           1      50      83      38

In [21]:
# priority wise sorting
my_data.sort_values(by=['MarksC','MarksA'],ascending=True)

Unnamed: 0  MarksA  MarksB  MarksC
2           2      43      97      28
3           3      43      75      34
1           1      50      83      38
0           0       8      81      64
4           4      43      51      64

In [22]:
# to get an array
data_array=my_data.values

In [23]:
print(data_array)

[[ 0  8 81 64]
 [ 1 50 83 38]
 [ 2 43 97 28]
 [ 3 43 75 34]
 [ 4 43 51 64]]


In [25]:
# to convert an array back to data frame
new_df=pd.DataFrame(data_array,dtype='float64',columns=['Sl No.','physics','chem','Maths'])

In [26]:
new_df

Sl No.  physics  chem  Maths
0     0.0      8.0  81.0   64.0
1     1.0     50.0  83.0   38.0
2     2.0     43.0  97.0   28.0
3     3.0     43.0  75.0   34.0
4     4.0     43.0  51.0   64.0

In [27]:
pd.DataFrame?

In [28]:
new_df.to_csv('PCM.csv',index=False)# so that we dont end up with an unwanted unnamed column